services:
  postgres:
    ports:
      - "5432:5432"

  prometheus:
    ports:
      - "9090:9090"

  redis:
    ports:
      - "6379:6379"

  app:
    environment:
      BASE_URL: "http://localhost:8080"
